// packages/angular/projects/emo-angular/src/lib/emo-angular.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'lib-emo-angular',
  templateUrl: './emo-angular.component.html',
  styles: [],
})
export class EmoAngularComponent {
  @Input('height') height!: number;
  @Input('width') width!: number;
  @Input('emoji') emoji!: string;
  url: string = `https://twemoji.maxcdn.com/v/latest/svg/${this.parse(
    this.emoji,
  )}.svg`;

  private parse(emoji?: string): string {
    if (emoji === undefined) {
      return '';
    }

    if (emoji.length === 1) {
      return emoji.charCodeAt(0).toString(16);
    }
    const comp =
      (emoji.charCodeAt(0) - 0xd800) * 0x400 +
      (emoji.charCodeAt(1) - 0xdc00) +
      0x10000;
    return (comp < 0 ? emoji.charCodeAt(0) : comp).toString(16);
  }

  constructor() {
    console.log(this.emoji);
  }
}

<img [src]="url" [alt]="emoji" [style.width]="width" [style.height]="height" />

// packages/vue/src/emo.vue
<script lang="ts">
import Vue from 'vue';

export default /*#__PURE__*/ Vue.extend({
  name: 'Emo', // vue component name
  props: ['emoji'], // props
  methods: {
    parse: (emoji: string): string => {
      if (emoji.length === 1) {
        return emoji.charCodeAt(0).toString(16);
      }
      const comp =
        (emoji.charCodeAt(0) - 0xd800) * 0x400 +
        (emoji.charCodeAt(1) - 0xdc00) +
        0x10000;
      return (comp < 0 ? emoji.charCodeAt(0) : comp).toString(16);
    },
  },
});
</script>

<template>
  <img
    :src="`https://twemoji.maxcdn.com/v/latest/svg/${parse(emoji)}.svg`"
    :alt="emoji"
  />
</template>

<style scoped>
img {
  display: inline-block;
  width: 1em;
  height: 1em;
  vertical-align: -0.1em;
  background-image: none;
  background-position: center;
  background-repeat: no-repeat;
  background-size: contain;
}
</style>
